import type { GameCardProps } from './components/GameCard';

export const gameData: GameCardProps[] = [
  {
    title: 'Tetris',
    description: 'The classic puzzle game where you combine falling blocks to clear lines.',
    image: '🧩',
    category: 'Puzzle',
    difficulty: 'Medium',
    players: '1 player',
    playTime: '5-30 min',
    href: '/tetris',
    isComingSoon: false,
  },
  {
    title: 'Snake Game',
    description: 'Classic game where you control a snake to eat food and grow longer.',
    image: '🐍',
    category: 'Action',
    difficulty: 'Easy',
    players: '1 player',
    playTime: '3-15 min',
    href: '/snake',
    isComingSoon: true,
  },
  {
    title: 'Breakout',
    description: 'Arcade game where you use a paddle to bounce a ball and break blocks.',
    image: '🎯',
    category: 'Arcade',
    difficulty: 'Easy',
    players: '1 player',
    playTime: '5-20 min',
    href: '/breakout',
    isComingSoon: true,
  },
  {
    title: '2048',
    description: 'Puzzle game where you combine number tiles to reach 2048.',
    image: '🔢',
    category: 'Puzzle',
    difficulty: 'Medium',
    players: '1 player',
    playTime: '10-30 min',
    href: '/2048',
    isComingSoon: true,
  },
  {
    title: 'Pac-Man',
    description: 'The classic action game where you race through a maze eating dots.',
    image: '👾',
    category: 'Arcade',
    difficulty: 'Medium',
    players: '1 player',
    playTime: '5-25 min',
    href: '/pacman',
    isComingSoon: true,
  },
  {
    title: 'Minesweeper',
    description: 'Logic game where you open all squares while avoiding hidden mines.',
    image: '💣',
    category: 'Puzzle',
    difficulty: 'Hard',
    players: '1 player',
    playTime: '5-30 min',
    href: '/minesweeper',
    isComingSoon: true,
  },
];
